# This is a basic workflow that is manually triggered

name: Download and push to cdn
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  schedule:
    - cron: "30 11 * * 4"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
        S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    # Runs a single command using the runners shell
    steps:

      
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun .
